[package]
name = "trash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.8", features = ["cargo"] }
serde = "1.0.155"
serde_derive = "1.0.155"
serde_json = "1.0.94"
